apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-library-api
  description: Tanzu Java Web App
  tags:
    - java
    - spring
    - web
    - tanzu
spec:
  type: service
  lifecycle: experimental
  owner: mccabe
