spring:
  application:
    name: tap-spring-demo
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: none
  datasource:
    driverClassName: org.h2.Driver
  flyway.enabled: true
